### ISSUE TITLE
Add default punctual light

### ISSUE THREAD

**Issue by UX3D-nopper** [ux3d/glTF-Sample-Viewer#143]
- [ ] By default off
- [ ] Should merge with exsiting punctual lights in a scene

**Comment by echadwick-wayfair** [comment]
Here is a glTF model with a directional light. I propose this orientation for the default punctual light.

The models also demonstrate KHR_materials_specular, but this can be ignored for now.

How it renders in Babylon.js Sandbox, with the IBL disabled:
![image](https://user-images.githubusercontent.com/40177036/108242654-27293600-711b-11eb-88c7-a5c73a556912.png)

[Specular_SpheresOnBoxes.zip](https://github.com/ux3d/glTF-Sample-Viewer/files/5997418/Specular_SpheresOnBoxes.zip)

**Comment by UX3D-nopper** [comment]
Scross check solution from Autodesk: https://knowledge.autodesk.com/support/3ds-max/getting-started/caas/CloudHelp/cloudhelp/2021/ENU/3DSMax-Basics/files/GUID-5FB7ABB0-DBCE-4344-802D-A5967FA62166-htm.html

**Comment by echadwick-wayfair** [comment]
I like the idea of two directional lights from opposing directions. It would be helpful if the fill light was lower intensity than the key. Here's a sample glTF with two directional lights if it helps:

[DirectionalLightsForSampleViewer.zip](https://github.com/ux3d/glTF-Sample-Viewer/files/5998059/DirectionalLightsForSampleViewer.zip)

![image](https://user-images.githubusercontent.com/40177036/108255924-de797900-712a-11eb-8ab5-c7be788e02f3.png)

**Comment by UX3D-nopper** [comment]
Can we find a decission on this on Wednesday?

**Comment by emackey** [comment]
Eric, would we want the fill light below the model like that?  I think it would be more natural for one to be upper-left and the other to be upper-right, perhaps at different elevations.

Other than the details of where exactly to place good-looking lights, I think the feature as Norbert describes sounds like a good, correct solution to the concerns that were discussed last week.

**Comment by echadwick-wayfair** [comment]
Yes.

This is also what the Autodesk default lighting does, which Norbert
referenced. Their fill light is at full strength, rather than the 1/2
strength that I'm proposing. My personal preference is to have the fill be
less strong than the key light.

Below: Autodesk default lighting in 3ds Max. In this case "Default Lights
Follow View Angle" is disabled, so the lights are static in world space. I
don't think we want the key light behind the model though.

[image: image.png]

Below: When "Default Lights Follow View Angle" is enabled, the key light is
always aligned to the camera, above and behind the camera's right shoulder.
I don't think we want this though, static lights are generally better in a
model viewer.

[image: image.png]

**Comment by emackey** [comment]
Hi Eric, these images didn't come through in email.  I think you'll need to drag & drop them directly on GitHub.  Thanks!

**Comment by echadwick-wayfair** [comment]
Thanks, trying again:


Yes.

This is also what the Autodesk default lighting does, which Norbert
referenced. Their fill light is at full strength, rather than the 1/2
strength that I'm proposing. My personal preference is to have the fill be
less strong than the key light.

Below: Autodesk default lighting in 3ds Max. In this case "Default Lights
Follow View Angle" is disabled, so the lights are static in world space. I
don't think we want the key light behind the model though.

![2021-02-24 15_34_56-Untitled - Autodesk 3ds Max 2020](https://user-images.githubusercontent.com/40177036/109071170-66c6c380-76c1-11eb-985d-d4bc071d877b.png)

Below: When "Default Lights Follow View Angle" is enabled, the key light is
always aligned to the camera, above and behind the camera's right shoulder.
I don't think we want this though, static lights are generally better in a
model viewer.

![2021-02-24 15_37_51-Untitled - Autodesk 3ds Max 2020](https://user-images.githubusercontent.com/40177036/109071195-6af2e100-76c1-11eb-9a8c-f5f5faced77f.png)

**Comment by UX3D-becher** [comment]
we have implemented this with #162
